### PR TITLE
feat: add extension catalog

### PR DESCRIPTION
**Pull request by ericswanson-dfinity**
Adds /catalog.json, which `dfx extension install` will use to locate extension.json.

Part of https://dfinity.atlassian.net/browse/SDK-1796

### CODE REVIEW

**Comment by aterga** [comment]
The term registry in the context of ICP is associated with the Registry canister (and things around that).

This feature seems to be unrelated to the Registry canister, so I think the naming might be confusing. 

Any chance we could re-negotiate the name?

**Comment by lwshang** [comment]
> This feature seems to be unrelated to the Registry canister, so I think the naming might be confusing.
>
> Any chance we could re-negotiate the name?

Hi @aterga.

IMO, "registry" is the most accurate term for its purpose. Could you come up with any alternatives?

---

This repo (`dfx-extensions`) is sort of a backend service to support the CLI tool `dfx extension install`.
Only very few people (SDK team, developers who build dfx extensions) in the community should be aware of this repo.

The majority of ICP community recognize "registry" as the Registry canister while a small group knows this "registry.json" file. So I don't think the potential "confusion" is a big issue. If it is desired, we can add some explanation in the README of this repo.

P.S. Currently, this repo serves as the home of the nns and sns extensions. As we are expecting more extensions from the community, we plan to make this repo a central registry of dfx extensions. Once it is in place (this PR merged) , the nns and sns extensions can be moved to their own repos. Then we can decouple the "dfx extension framework" and the individual extensions. NNS team won't have to keep an eye on this repo.

**Comment by aterga** [comment]
> > This feature seems to be unrelated to the Registry canister, so I think the naming might be confusing.
> > Any chance we could re-negotiate the name?
> 
> IMO, "registry" is the most accurate term for its purpose. Could you come up with any alternatives?

How about "catalog"? (I'd be fine with any other synonym that doesn't collide with existing IC concepts). 

> This repo (`dfx-extensions`) is sort of a backend service to support the CLI tool `dfx extension install`. Only very few people (SDK team, developers who build dfx extensions) in the community should be aware of this repo.

One could argue that this si a public repo and thus we don't know if many people will stumble upon this while googling, e.g., "dfx registry" (while trying to find, e.g., how to install or interact with the Registry canister using DFX). 

To be clear, what you're doing in the PR makes sense to me, it's just the naming that I think is suboptimal. Given that this repo, as you say, isn't currently used by many people, maybe renaming isn't going to be too difficult?

**Comment by lwshang** [comment]
> How about "catalog"? 

Sounds good to me. However, I believe Eric should make the final decision.

**Review by lwshang — APPROVED** [review]

**Pull request merged**
